apiVersion: v1
kind: Service
metadata:
  name: ci-app
spec:
  ports:
  - port: 9999
    protocol: TCP
    targetPort: 9999
  selector:
    app: ci-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ci-app
  template:
    metadata:
      labels:
        app: ci-app
    spec:
      containers:
      - image: lucasmsp/tp2:latest
        imagePullPolicy: Always #Never
        name: ci-app
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: url_model
          value: "https://github.com/lucasmsp/ci-test/raw/master/app/model/model.pkl"
        - name: url_column_model
          value: "https://github.com/lucasmsp/ci-test/raw/master/app/model/model_columns.pkl"
        - name: version_model
          value: "3"
        ports:
        - containerPort: 9999
          name: flask
      restartPolicy: Always
             

