
apiVersion: v1
kind: Service
metadata:
  name: ci-app
spec:
  ports:
  - port: 9999
  selector:
    app: ci-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ci-app
  template:
    metadata:
      labels:
        app: ci-app
    spec:
      containers:
      - image: lucasmsp/tp2:latest
        imagePullPolicy: Always
        name: ci-app
