apiVersion: v1
kind: Service
metadata:
  name: ci-app
spec:
  # type: NodePort # Expose services to outside
  ports:
  - port: 9999
    #nodePort: 31111
  selector:
    app: ci-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ci-app
  template:
    metadata:
      labels:
        app: ci-app
    spec:
      containers:
      - image: lucasmsp/tp2:latest
        imagePullPolicy: Always
        name: ci-app
        env:
        - name: url_model
          value: "https://github.com/lucasmsp/ci-test/raw/master/app/model/model.pkl"
        - name: url_column_model
          value: "https://github.com/lucasmsp/ci-test/raw/master/app/model/model_columns.pkl"
        - name: version_model
          value: "2"
      restartPolicy: Always
             

